#!/usr/bin/python

import optparse
import os
import socket
import sys

ATHINFO_FALLBACK_PORT = 49155

def main():
    parser = optparse.OptionParser(
        usage='%prog [options] host query'
        )
    parser.add_option(
        '-t', '--timeout',
        type='float',
        dest='timeout',
        help='timeout after SECONDS',
        metavar='SECONDS',
        )

    (options, args) = parser.parse_args()
    if len(args) != 2:
        parser.print_usage()
        return 1
    host = args[0]
    query = args[1]

    socket.setdefaulttimeout(options.timeout)

    try:
        port = socket.getservbyname('athinfo', 'tcp')
    except socket.error:
        port = ATHINFO_FALLBACK_PORT

    try:
        host_addr = socket.gethostbyname(host)
    except socket.error:
        print >>sys.stderr, 'athinfo: host %s not found' % host
        return 1

    try:
        s = socket.socket()
        s.connect((host_addr, port))
        s.sendall('%s\n' % query)
        sys.stdout.write(s.makefile().read())
    except socket.error, e:
        print >>sys.stderr, 'athinfo: %s' % e.args[-1]
        return 1
    except KeyboardInterrupt:
        return 1


if __name__ == '__main__':
    sys.exit(main())
