.\" $Id: athinfo.1,v 1.5 2006-05-22 18:20:35 amb Exp $
.\"
.\" Copyright 1998-2009 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH ATHINFO 1 "11 April 2009"
.SH NAME
athinfo \- Retrive information about a workstation
.SH SYNOPSIS
.B athinfo [-t \fIsecs\fP] \fIhost\fP \fIquery\fP
.SH OPTIONS
.IP "-t secs"
timeout for establishing a connection
.SH DESCRIPTION
.B athinfo
retrieves information from a workstation running the athinfo daemon
(see
.BR athinfod (8)).
Standard queries implemented on Athena workstations typically include:
.RS
.TP 17
.B queries
The athinfo queries defined on the workstation
.TP 17
.B uname
The workstation's "uname -a" output
.TP 17
.B machtype
The platform name of the workstation
.TP 17
.B sysname
The Athena system name of the workstation
.TP 17
.B cpuspeed
The currently reported CPU speed of the workstation (may vary)
.TP 17
.B cputype
The CPU type of the workstation
.TP 17
.B display
The type of display on the workstation
.TP 17
.B disks
The types of disks attached to the workstation
.TP 17
.B memory
The amount of physical memory in the workstation
.TP 17
.B swap
The workstation's swap configuration and free swap space
.TP 17
.B modules
The workstation's currently-loaded kernel modules
.TP 17
.B packages
The workstation's installed package list
.TP 17
.B rc.conf
The contents of the workstation's Athena rc.conf file
.TP 17
.B version
The contents of the workstation's Athena version file
.TP 17
.B clusterinfo
The contents of the workstation's cached cluster information in C
shell format.
.TP 17
.B clusterinfo.bsh
The contents of the workstation's cached cluster information in Bourne
shell format.
.TP 17
.B services
The contents of the workstation's .services file
.TP 17
.B update.log
The contents of the workstation's update log (only works if the
workstation is set PUBLIC=true or is debathena-cluster)
.TP 17
.B reactivate.log
The contents of the workstation's reactivate log (only works if the
workstation is set PUBLIC=true or is debathena-cluster)
.TP 17
.B update-status
On Debian/Ubuntu systems only, result of a simulated apt upgrade,
including whether any packages were going to be upgraded. Note that
this does not run aptitude update first!
.TP 17
.B policy
On Debian/Ubuntu systems only, the apt repository policy, including
all configured apt repositories/components and their priorities
.TP 17
.B hardware
On Linux, the hardware's self-reported product name and version, from
the DMI/SMBIOS interface
.TP 17
.B update.desync
The contents of the workstation's update.desync file, if any
.TP 17
.B install.log
The contents of the workstation's install log
.TP 17
.B date
The workstation's local time
.TP 17
.B uptime
The workstation's uptime, number of users, and load average
.TP 17
.B partitions
The partition setup of the workstation's root disk
.TP 17
.B df
The disk usage on the Athena-defined partitions of the workstation
.TP 17
.B interfaces
The status of the workstation's network interfaces
.TP 17
.B routes
The workstation's routing table
.TP 17
.B listeners
A list of the workstation's TCP server sockets
.TP 17
.B login
0 if logins on the workstation are enabled; 1 if not
.TP 17
.B patches
On Solaris workstations only, the workstation's patch revision information
.TP 17
.B prom
On Solaris workstations only, PROM version information
.TP 17
.B update.pkglog
On Solaris workstations only, the contents of the workstation's package
update log (only works if the workstation is set PUBLIC=true)
.TP 17
.B rvdinfo
On Solaris workstations only, the contents of the .rvdinfo file on the
workstation's system packs
.TP 17
.B verify.log
On Red Hat workstations only, the contents of the workstation's boot-time
public workstation verification log
.TP 17
.B xconf
On Red Hat public workstations only, the contents of the workstation's X11
configuration.
.TP 17
.B hinv
On IRIX workstations only, displays the workstation's verbose hardware
profile
.TP 17
.B instmach
On IRIX workstations only, displays the machine variable settings
determined by inst
.TP 17
.B instmachinv
On IRIX workstations only, displays the machine variable settings used
by inst the last time it ran
.TP 17
.B chkconfig
On IRIX workstations only, displays the configuration settings set in
.BR /etc/config
.RE
.SH "SEE ALSO"
.BR athinfod (8)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998 by the Massachusetts Institute of Technology.
